server:
  port: 9099
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  messages:
    basename: cn.kinkii.novice.framework.i18n.messages,cn.kinkii.novice.security.i18n.messages,cn.kinkii.novice.security.i18n.responses
    cache-duration: 3600
    encoding: utf-8
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      fail_on_empty_beans: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fk_visitor?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: fk-visitor
    password: 'P@ssw0rd'
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 10000
      auto-commit: true
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 10
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      max-file-size: 10000MB
      max-request-size: 1000MB
novice:
  k-security:
    public-urls: /pub/**,/personal/**,/swagger-resources/**,/v2/*,/swagger*,/webjars/**,/openpage/**
    token-jwt:
      sign-key: phoenixforce
      access-expires: 86400
    auth:
      password-encoder: plain
  k-accessory:
    cloopen:
      enable: true
      sid: 8a216da86f17653b016f17fc82c1010d
      token: fb099703172b4c57b464c13c4d723edd
      appId: 8a216da86f17653b016f17fc83240113
    vcode:
      enable: true
      sender:
        supplier: cloopen
        type: sms
        detail:
          template: 574022
    sms:
      template:
        t1: 621152
project:
  basic:
    name: fk-visitor
    debug: true
  upload:
    path: /data/apps/upload/
    url: http://10.240.68.100:89/
